/**
 * Refresh the vendored model-price snapshot from LiteLLM's community-maintained
 * price map (the de-facto source — same data ccusage et al. use). We do NOT
 * hand-maintain prices: run this to regenerate `src/providers/prices.generated.ts`.
 *
 *   bun scripts/refresh-prices.ts
 *
 * It fetches the full LiteLLM map, keeps only the providers agent-loop ships
 * (anthropic / deepseek / openai), converts per-token → per-1M, and writes a
 * small typed snapshot. Prices change; rerun periodically. Unknown models stay
 * absent → cost is reported as n/a, never guessed.
 */
const SOURCE =
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";
const PROVIDERS = new Set(["anthropic", "deepseek", "openai"]);
const MODES = new Set(["chat", "completion", "responses"]);

type Raw = {
  litellm_provider?: string;
  mode?: string;
  input_cost_per_token?: number | null;
  output_cost_per_token?: number | null;
  cache_read_input_token_cost?: number | null;
  cache_creation_input_token_cost?: number | null;
};

const per1M = (v: number | null | undefined): number | undefined =>
  typeof v === "number" ? Math.round(v * 1e6 * 1e6) / 1e6 : undefined;

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`fetch ${SOURCE} failed: ${res.status}`);
const all = (await res.json()) as Record<string, Raw>;

const out: Record<
  string,
  { inputPer1M: number; outputPer1M: number; cacheReadPer1M?: number; cacheWritePer1M?: number }
> = {};
for (const [key, m] of Object.entries(all)) {
  if (!m || typeof m !== "object") continue;
  if (!PROVIDERS.has(m.litellm_provider ?? "")) continue;
  if (m.mode && !MODES.has(m.mode)) continue;
  const inputPer1M = per1M(m.input_cost_per_token);
  const outputPer1M = per1M(m.output_cost_per_token);
  if (inputPer1M === undefined || outputPer1M === undefined) continue;
  const cacheReadPer1M = per1M(m.cache_read_input_token_cost);
  const cacheWritePer1M = per1M(m.cache_creation_input_token_cost);
  out[key.toLowerCase()] = {
    inputPer1M,
    outputPer1M,
    ...(cacheReadPer1M !== undefined ? { cacheReadPer1M } : {}),
    ...(cacheWritePer1M !== undefined ? { cacheWritePer1M } : {}),
  };
}

const date = new Date().toISOString().slice(0, 10);
const body = Object.keys(out)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`)
  .join("\n");
const file = `// AUTO-GENERATED by scripts/refresh-prices.ts — do not edit by hand.
// Source: LiteLLM model_prices_and_context_window.json
// Snapshot: ${date}. Values are USD per 1,000,000 tokens. Rerun the script to refresh.
export interface ModelPriceEntry {
  inputPer1M: number;
  outputPer1M: number;
  cacheReadPer1M?: number;
  cacheWritePer1M?: number;
}

export const MODEL_PRICES: Record<string, ModelPriceEntry> = {
${body}
};
`;
await Bun.write(new URL("../src/providers/prices.generated.ts", import.meta.url), file);
console.log(`wrote ${Object.keys(out).length} models to src/providers/prices.generated.ts (${date})`);
