export type { CommandContext, CommandError, CommandErrorCode, CommandResult } from "./types";
export { fail, ok } from "./types";

export {
  createWorkspace,
  deleteWorkspace,
  getWorkspace,
  listWorkspaces,
  type CreateWorkspaceInput,
  type WorkspaceIdInput,
} from "./workspace";

export {
  addWorkspacePreference,
  listWorkspacePreferences,
  removeWorkspacePreference,
  type AddWorkspacePreferenceInput,
  type RemoveWorkspacePreferenceInput,
} from "./preference";

export {
  acceptPlan,
  acceptStageReview,
  acceptTask,
  completeWorkerRun,
  createTask,
  exceedWorkerRunBudget,
  failWorkerRun,
  getTask,
  inspectTaskCompact,
  inspectTaskEvents,
  inspectTaskProjection,
  inspectTaskSummary,
  inspectTaskTrace,
  listTasks,
  recommendFinalReview,
  recordRuntimeProcessFinished,
  recordRuntimeProcessStarted,
  rejectPlan,
  rejectStageReview,
  rejectTask,
  startStageReview,
  startWorkerRun,
  submitPlan,
  waitTask,
  type FinishStageReviewInput,
  type FinishTaskInput,
  type FinishWorkerRunInput,
  type ListTasksInput,
  type PlanDecisionInput,
  type RecommendFinalReviewInput,
  type RecordRuntimeProcessFinishedInput,
  type RecordRuntimeProcessStartedInput,
  type RejectPlanInput,
  type StageReviewInput,
  type StartWorkerRunInput,
  type CreateTaskInput,
  type InspectTaskTraceInput,
  type SubmitPlanInput,
  type TaskCompactNextAction,
  type TaskCompactView,
  type TaskIdInput,
  type TaskSummary,
  type TaskTraceEntry,
  type WaitTaskInput,
} from "./task";
