#!/usr/bin/env bun
/**
 * Install an accepted Sikong promotion candidate as local stable.
 *
 * This is local dogfood promotion only. It does not publish npm packages and it
 * does not mutate the global npm `sikong` command. By default it installs under
 * `${SIKONG_HOME:-~/.sikong}/local-stable`.
 */
import { mkdir } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildPromotionInstallPlan,
  installPromotionCandidate,
  readPromotionEvidence,
  validatePromotionEvidenceForInstall,
  verifyCandidateBinaryHash,
} from "../src/promotion-install";
import { defaultWorkspaceHome } from "../src/workspace-layout";
import { runCommandEvidence } from "../src/promotion-evidence";

const PKG_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO_ROOT = dirname(dirname(PKG_ROOT));
const argv = process.argv.slice(2);

function flag(name: string): string | undefined {
  const index = argv.indexOf(name);
  return index >= 0 ? argv[index + 1] : undefined;
}

function hasFlag(name: string): boolean {
  return argv.includes(name);
}

function usage(): never {
  console.error(
    [
      "usage: bun scripts/promotion-install-local.ts --evidence <json> --accepted-by <name> [--reason <text>] [--install-root <dir>]",
      "",
      "  --evidence <json>     Promotion evidence JSON generated by promotion:evidence.",
      "  --accepted-by <name>  Lead identity approving local stable replacement.",
      "  --reason <text>       Optional acceptance note.",
      "  --install-root <dir>  Defaults to ${SIKONG_HOME:-~/.sikong}/local-stable.",
    ].join("\n"),
  );
  process.exit(2);
}

if (hasFlag("--help")) usage();

const evidenceArg = flag("--evidence");
const acceptedBy = flag("--accepted-by") ?? "";
const reason = flag("--reason");
const installRoot = resolve(flag("--install-root") ?? `${defaultWorkspaceHome()}/local-stable`);

if (!evidenceArg) usage();
const evidenceFile = evidenceArg;

async function currentHead(): Promise<string> {
  const result = await runCommandEvidence("git rev-parse HEAD", ["git", "rev-parse", "HEAD"], REPO_ROOT);
  if (result.exitCode !== 0) throw new Error("failed to read current git HEAD");
  return result.stdoutPreview.trim();
}

async function main(): Promise<void> {
  const evidencePath = resolve(REPO_ROOT, evidenceFile);
  const { raw, evidence } = await readPromotionEvidence(evidencePath);
  const sha = await currentHead();
  const issues = validatePromotionEvidenceForInstall(evidence, raw, {
    repoRoot: REPO_ROOT,
    currentSha: sha,
    acceptedBy,
  });
  if (issues.length) {
    console.error("promotion install rejected:");
    for (const issue of issues) console.error(`- ${issue}`);
    process.exit(1);
  }

  await mkdir(installRoot, { recursive: true });
  const plan = buildPromotionInstallPlan({
    repoRoot: REPO_ROOT,
    evidencePath,
    acceptedBy,
    reason,
    installRoot,
    currentSha: sha,
  }, evidence);
  const hashIssues = await verifyCandidateBinaryHash(plan.sourceBin, evidence.candidate.sha256);
  if (hashIssues.length) {
    console.error("promotion install rejected:");
    for (const issue of hashIssues) console.error(`- ${issue}`);
    process.exit(1);
  }
  await installPromotionCandidate(plan);

  console.log("local stable installed");
  console.log(`version: ${plan.receipt.packageVersion}`);
  console.log(`git: ${plan.receipt.gitSha}`);
  console.log(`current: ${plan.receipt.currentLink}`);
  console.log(`receipt: ${relative(installRoot, plan.receiptPath).replaceAll("\\", "/")}`);
}

await main();
